### ISSUE TITLE
Different usernames can see the same stored files if same mnemonic

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#85] opened 2022-09-21 09:59 UTC
This situation should probably not exist, so will label as bug.

Restoring account with same mnemonic but under different usernames, the same data is seen under Fairdrive app.
E.g., users:
fairos-demouser2
fairos-demouser3 
Can see the same folder, created under demouser2

**Comment by tfius** [comment] 2022-09-21 12:01
this is bad, should not happen

**Comment by tfius** [comment] 2022-09-21 12:17
ok, now i understand, this is by design, same key for all users, same derivation from them. The key is important. Even if you provide different username, mnemonic will be the same, address will be the same and all derived keys are same. This is a feature. @asabya mentioned this a while ago. Closing.

**Closed by tfius** 2022-09-21 12:17 UTC
Labels: bug
